최종 5챕터 번역
mingrammer/gobyexample pull request #2
Opened 2017-01-29 12:17 UTC by Suckzoo

작업중이며, 1시간 내로 작업 끝내고 노티 드리겠습니다.
- [v] 환경 변수
- [ ] 프로세스 생성
- [ ] 프로세스 실행
- [ ] 시그널
- [ ] 종료

환경변수
 프로세스 생성
 프로세스 실행
 시그널
 종료

2017-01-29 12:19 UTC, mingrammer commented
네 감사합니다~

2017-01-29 13:36 UTC, Suckzoo commented
@mingrammer 피드백 부탁드리겠습니다!
빠르게 작업하느라 오역이나 어색한 번역이 있을 수 있습니다. 미리 양해를 구합니다 ㅜㅜ

2017-01-29 14:27 UTC, mingrammer requested changes
`string`은 `문자열`로 통일해주세요!

2017-01-29 14:27 UTC, mingrammer requested changes
`리턴`은 `반환`으로 통일해주세요! (이전의 모든 예제가 `반환`을 사용하고 있습니다)

2017-01-29 14:29 UTC, mingrammer requested changes
문서 내의 링크들은 `chapter` -> `/gobyexample/chapter`의 포맷으로 변경하셔야 합니다~!

2017-01-29 14:30 UTC, mingrammer requested changes

2017-01-29 14:30 UTC, mingrammer commented on examples/execing-processes/execing-processes.sh
> +#  웬만해서 문제가 되지 않을 것입니다.
웬만해서 > 웬만해선

2017-01-29 14:32 UTC, mingrammer requested changes

2017-01-29 14:32 UTC, mingrammer commented on examples/exit/exit.sh
> +#  exit 값를 `go`가 가져가서 출력될 것입니다.
exit 값를 > exit 값을

2017-01-29 14:32 UTC, mingrammer requested changes

2017-01-29 14:32 UTC, mingrammer commented on examples/exit/exit.sh
> +# binary를 build하여 실행시키는 경우, 터미널에서
`binary`와 `build`는 각각 `바이너리`와 `빌드`로 통일해주세요!

2017-01-29 14:35 UTC, mingrammer commented on examples/signals/signals.go
> +//  여기서는 Go가 채널을 이용하여 signal을 다루는 것을 보도록 하겠습니다.
"여기서는 채널을 이용하여 signal을 다루는 방법을 살펴보겠습니다"가 자연스러울 것 같습니다~

2017-01-29 14:41 UTC, mingrammer requested changes

2017-01-29 14:41 UTC, mingrammer commented on examples/signals/signals.go
> +	//  종료 가능하다고 알려줄 것입니다.
"이 고루틴은 signal을 받기 위한 블로킹 고루틴입니다. Signal을 받으면 받은 signal을 출력하고 프로그램에 종료 가능함을 알려줄 것입니다."

goroutine과 blocking은 이전 예제에서 각각 고루틴, 블로킹으로 통일하였습니다

2017-01-29 14:42 UTC, mingrammer requested changes

2017-01-29 14:42 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.go
> +// 되었습니다. Go에서 다른 프로세스를 띄우는 몇몇 예제를 살펴봅시다.
몇몇 > 몇 가지

2017-01-29 14:43 UTC, mingrammer requested changes

2017-01-29 14:43 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.go
> +	//  가져오는데 사용되는 유유용한 도구입니다. 에러가 없다면
유유용한 > 유용한

2017-01-29 14:45 UTC, mingrammer requested changes

2017-01-29 14:45 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.go
> +	//  `dateOut`에는 날짜 정보를 담은 byte들을 들고있을 것입니다.
"`dateOut`은 날짜 정보를 담은 바이트를 저장할겁니다."가 자연스러울 것 같습니다

2017-01-29 14:49 UTC, mingrammer requested changes

2017-01-29 14:49 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.go
> +	//  `StderrPipe`의 결과도 똑같은 방법으로 볼 수 있습니다.
위예 예제에서 에러 체크는 생략했지만, 모든 경우에 대해 `if err != nil` 패턴을 사용할 수 있습니다.
또한 우리는 `StdoutPipe`의 결과만 수집했지만, 정확히 같은 방법으로 `StderrPipe`의 결과도 수집할 수 있습니다.

2017-01-29 14:51 UTC, mingrammer requested changes

2017-01-29 14:51 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.go
> +	//  string 하나를 제공한다는 점을 기억하세요.
argument > 인자
argument array > 인자 배열
command > 커맨드
string > 문자열
로 통일해주세요!

2017-01-29 14:52 UTC, mingrammer requested changes

2017-01-29 14:52 UTC, mingrammer commented on examples/spawning-processes/spawning-processes.sh
> +#  완벽히 똑같은 output을 리턴합니다.
생성된 프로그램은 우리가 커맨드라인에서 실행한 것과 정확히 동일한 출력값을 반환합니다.

2017-01-29 14:52 UTC, mingrammer requested changes

2017-01-29 14:52 UTC, mingrammer commented on examples/signals/signals.go
> +//  여기서는 Go가 채널을 이용하여 signal을 다루는 것을 보도록 하겠습니다.
command > 커맨드
command-line > 커맨드라인
으로 통일해주세요!

2017-01-29 14:53 UTC, mingrammer commented
@Suckzoo 리뷰 달았습니다!

2017-01-29 14:56 UTC, Suckzoo commented
@mingrammer 확인했습니다. 내일 저녁까지 반영하고 멘션 드리도록 하겠습니다.

2017-01-29 14:57 UTC, mingrammer commented
네넵 :D

2017-01-30 12:44 UTC, Suckzoo commented
@mingrammer 피드백 전부 반영했습니다! 체크 부탁드려요~

2017-01-30 14:33 UTC, mingrammer approved these changes

2017-01-30 14:34 UTC, merged

2017-01-30 14:34 UTC, mingrammer commented
@Suckzoo 감사합니다~. 제가 최종 빌드하겠습니다 ~담엔 홍보를~